name: Fetch Credly Badges and Update README

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-credly-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Badges from Credly
        uses: michaelcontento/credly-import-action@v1
        with:
          username: pratik-tamgole
          datafile: data/CredlyBadges.json
          imagedir: assets/badges

      - name: Update README with Badge Data
        run: |
          python3 update_readme.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "pat-glitch"
          git config user.email "pratiktamgole@gmail.com"
          git add README.md
          git commit -m "Update README with latest badges"
          git push
